dependencies:
  shared:
    default:
      r2.1:
      r2.3:
      r2.4:
    dev:
      shared:
        - gem: metadata-json-lint
          version: '>= 2.0.1 < 3.0.0'
        - gem: mocha
          version: '>= 1.0.0 < 1.2.0'
        - gem: parallel_tests
        - gem: pry
        - gem: gettext-setup
        - gem: puppet-lint
          version: '>= 2.3.0 < 3.0.0'
        - gem: puppet-syntax
          version: '>= 2.4.1 < 3.0.0'
        - gem: puppetlabs_spec_helper
          version: '>= 1.2.1 < 2.0.0'
        - gem: specinfra
          version: '2.67.3'
        - gem: rspec-puppet
          version: '>= 2.3.2 < 3.0.0'
        - gem: rspec-puppet-facts
          version: '~> 1.8'
        - gem: rainbow
          version: '>= 2.0.0 < 2.2.0'
        - gem: rubocop
        - gem: rubocop-rspec
          version: '~> 1.15'
        - gem: rspec_junit_formatter
          version: '~> 0.2'
      r2.1:
      r2.3:
      r2.4:
    system:
      shared:
        - gem: beaker-puppet_install_helper
        - gem: beaker-module_install_helper
        - gem: master_manipulator
      r2.1:
      r2.3:
      r2.4:
  posix:
    default:
      r2.1:
      r2.3:
      r2.4:
    dev:
      shared:
        - gem: simplecov
      r2.1:
      r2.3:
      r2.4:
    system:
      r2.1:
      r2.3:
      r2.4:
  win:
    default:
      shared:
        - gem: win32-dir
          version: '<= 0.4.9'
        - gem: win32-eventlog
          version: '<= 0.6.5'
        - gem: win32-process
          version: '<= 0.7.5'
        - gem: win32-security
          version: '<= 0.2.5'
        - gem: win32-service
          version: '<= 0.8.8'
      r2.1:
        - gem: nokogiri
          version: '1.7.2'
      r2.3:
      r2.4:
    dev:
      r2.1:
      r2.3:
      r2.4:
    system:
      r2.1:
      r2.3:
      r2.4:
